name: Testing

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
        
      - name: Debug - Imprimir requerimientos
        run: cat requirements.txt
      
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Some dependencies failed to install"
        
      
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV


      - name: Run tests
        run: |
          python3 manage.py test
