name: Testing

on:
  push:
    branches: ["tests"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extraer código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Depurar - Imprimir requisitos
        run: cat requirements.txt

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Agregar DATABASE_URL desde secretos
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Verificar DATABASE_URL (opcional)  # Paso opcional
        run: echo "DATABASE_URL: $DATABASE_URL"

      - name: Ejecutar pruebas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python3 manage.py test
